#!/usr/bin/env bash
# Copy the canonical ACS v1 library into each consuming plugin, or check that the
# copies still match. See standards/agent-config.md.
#
#   vendor.sh sync    refresh every vendored copy from the canonical files
#   vendor.sh check   exit non-zero if any copy has drifted (no writes)
#
# A vendored file is a fixed header, a sentinel line, then the canonical bytes
# verbatim. Everything below the sentinel must compare equal — that is the whole
# contract, and it is what makes drift mechanically detectable.
set -euo pipefail

SENTINEL="// ---- end vendored header — canonical bytes follow, byte-for-byte ----"
ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
CANON="$ROOT/plugins/agent-config/skills/agent-config/lib"

# Each consumer's vendor directory, relative to ROOT.
CONSUMERS=(
  "plugins/fellow/skills/fellow/scripts/lib/vendor/agent-config"
  "plugins/herdr/skills/herdr/scripts/lib/vendor/agent-config"
  "plugins/orchestrate/skills/orchestrate/scripts/lib/vendor/agent-config"
)
FILES=(config.ts credentials.ts)

header() { # $1 = filename
  cat <<EOF
// VENDORED COPY — do not edit this file.
//
// Canonical source: plugins/agent-config/skills/agent-config/lib/$1
// Refresh with:     plugins/agent-config/skills/agent-config/scripts/vendor.sh sync
// Verify with:      plugins/agent-config/skills/agent-config/scripts/vendor.sh check
//
// Edits made here are silently overwritten by the next sync. Fix the canonical copy.
$SENTINEL
EOF
}

# Strip the header: print everything after the sentinel line.
body() { sed "1,/^$(printf '%s' "$SENTINEL" | sed 's/[[\.*^$/]/\\&/g')\$/d" "$1"; }

mode="${1:-}"
case "$mode" in
  sync)
    for dir in "${CONSUMERS[@]}"; do
      mkdir -p "$ROOT/$dir"
      for f in "${FILES[@]}"; do
        { header "$f"; cat "$CANON/$f"; } > "$ROOT/$dir/$f"
        echo "synced  $dir/$f"
      done
    done
    ;;
  check)
    drift=0
    for dir in "${CONSUMERS[@]}"; do
      for f in "${FILES[@]}"; do
        target="$ROOT/$dir/$f"
        if [[ ! -f "$target" ]]; then
          echo "MISSING $dir/$f"; drift=1; continue
        fi
        if diff -q <(body "$target") "$CANON/$f" >/dev/null; then
          echo "ok      $dir/$f"
        else
          echo "DRIFTED $dir/$f"
          diff <(body "$target") "$CANON/$f" | head -20 || true
          drift=1
        fi
      done
    done
    [[ $drift -eq 0 ]] || { echo; echo "Vendored copies are out of date. Run: vendor.sh sync"; exit 1; }
    echo; echo "All vendored copies match the canonical library."
    ;;
  *)
    echo "usage: vendor.sh {sync|check}" >&2; exit 2 ;;
esac
